# Generated by Django 5.2.4 on 2025-07-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='lga_of_origin',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='state_of_origin',
        ),
    ]
