# Generated by Django 5.2.4 on 2025-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customerdetails_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='_bvn',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
