# Generated by Django 5.1.7 on 2025-07-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0003_transactions_account_delete_userids'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
