# Generated by Django 5.2.4 on 2025-07-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0004_account_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
