# Generated by Django 5.2.4 on 2025-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0005_delete_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acct_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
