# Generated by Django 5.2.4 on 2025-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0006_account_acct_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acct_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
