# Generated by Django 5.2.4 on 2025-07-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0007_account_acct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acct_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acct_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.CharField(default='', max_length=50, verbose_name='Bank Name'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('narration', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mono.account')),
            ],
        ),
    ]
